# Generated by Django 5.0.6 on 2024-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmidata',
            name='user_id',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
