# Generated by Django 5.0.6 on 2024-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bmidata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmidata',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
